### ISSUE TITLE
repository is empty

### ISSUE THREAD

**Issue by barbierb** [michel-meneses/keyword-miner#1]
Hello i just found out your repository and it appears that it is empty or files are missing.
I would really like to personnaly test this project myself, is it possible ?

Thanks.

**Comment by michel-meneses** [comment]
Hello! Sorry for the delayed reply. You can check the implementation of this project on [branch dev](https://github.com/michel-meneses/keyword-miner/tree/dev). Soon, it should be merged into the main branch.
